
[general]
	#Enable/Disable ReplayMod Support
	enabled = true
	#Internal Version Number. NO TOUCHY!
	version = 1

#The Replay Browser Event
[replay_viewer]
	#Enable/Disable the ReplayMod Replay Viewer Event
	enabled = true
	#The first line of text under the app name
	description = "Просматривает записи"
	#The second line of text under the app name
	state = "%player% просматривает библиотеку"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["mclogonew"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Это майнкрафт %mcver%, но модифицированный"
	#The Asset ID of the image to display as the small image
	smallImageKey = ["mclogo"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% моды установлены"
	#The buttons to display on Discord
	buttons = []

#The Replay Editor Event
[replay_editor]
	#Enable/Disable the ReplayMod Editor Event
	enabled = true
	#The first line of text under the app name
	description = "Редактирует запись"
	#The second line of text under the app name
	state = "%player% пересматривает запись"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["mclogonew"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Это майнкрафт %mcver%, но модифицированный"
	#The Asset ID of the image to display as the small image
	smallImageKey = ["mclogo"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% моды установлены"
	#The buttons to display on Discord
	buttons = []

#The Replay Rendering Event
[replay_render]
	#Enable/Disable the ReplayMod Rendering Event
	enabled = true
	#The first line of text under the app name
	description = "Экспортирует запись"
	#The second line of text under the app name
	state = "Рендеринг %replayframe%/%replaytotal% кадров"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["mclogonew"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Это майнкрафт %mcver%, но модифицированный"
	#The Asset ID of the image to display as the small image
	smallImageKey = ["mclogo"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% моды установлены"
	#The buttons to display on Discord
	buttons = []

