debug = false
disable_crowdin = false
check_for_updates = true

[activations.4aec07ba-d109-3345-9a0a-92022a116cd0]
toggle = false
type = "VOICE"
[activations.46927964-3207-377a-84d7-26a82d52be1e]
toggle = false
type = "VOICE"
[[key_bindings]]
name = "key.plasmovoice.general.mute_microphone"
any_context = false
category = "key.plasmovoice.general"

[[key_bindings.keys]]
code = 78
type = "KEYSYM"

[servers.8ea7a6b6-35b6-4c55-b412-b79cd20a5163.distances]
4aec07ba-d109-3345-9a0a-92022a116cd0 = 32


[voice]
disabled = false
microphone_disabled = true
activation_threshold = -50.0
input_device = ""
output_device = ""
disable_input_device = false
use_javax_input = false
microphone_volume = 2.0
noise_suppression = false
volume = 1.0
compressor_limiter = true
sound_occlusion = false
directional_sources = false
hrtf = false
stereo_capture = false

[voice.volumes.source_c8db8d73-9288-45cd-982c-4c52f89eeb19]
volume = 1.0
[voice.volumes.source_6da00a04-5869-4841-aaaf-0ca1661be3c7]
volume = 1.0
[voice.volumes.proximity]
volume = 1.0
[voice.volumes.source_25966168-dc9c-360c-8f32-ed022bfa1070]
volume = 1.0
[voice.volumes.groups]
volume = 1.0
[voice.volumes.source_303aa8cf-23a6-4984-8c55-8cecd5dbffc9]
volume = 1.0
[voice.volumes.source_f8c3f810-4790-4515-8da7-55ce6198cd1a]
volume = 1.0
[voice.volumes.discs]
volume = 1.0

[advanced]
visualize_voice_distance = false
visualize_voice_distance_on_join = false
compressor_threshold = -10
limiter_threshold = -6
directional_sources_angle = 145
stereo_sources_to_mono = false
panning = true
camera_sound_listener = true
exponential_volume_slider = true
exponential_distance_gain = true

[overlay]
show_activation_icon = true
activation_icon_position = "BOTTOM_LEFT"
show_source_icons = 0
show_static_source_icons = true
overlay_enabled = true
overlay_position = "TOP_LEFT"
overlay_style = "NAME_SKIN"

[overlay.source_states]
proximity = "OFF"
groups = "WHEN_TALKING"
discs = "OFF"
